// Shared profile data — used by all three directions
window.PROFILE = {
  name: "A. Antony Alosanai Promilton",
  honorific: "Dr.",
  shortName: "Promilton",
  titleLine: "Hydrogeologist · Consultant Geophysicist · Geospatial Researcher",
  degree: "Ph.D. in Geology",
  location: "Thoothukudi, Tamil Nadu, India",
  email: "geopromilton@gmail.com",
  phone: "+91 99623 53227",
  phone2: "+91 82481 28907",
  address: "3/25, Antoniar Kebi Street, Mela Arasadi Po. Vellapatti, Thoothukudi, Tamil Nadu – 628002, India",
  orcid: "0000-0002-6762-0103",
  links: {
    email: "mailto:geopromilton@gmail.com",
    github: "https://github.com/Geopromilton",
    linkedin: "https://www.linkedin.com/in/a-antony-alosanai-promilton-24a4a412a/",
    researchgate: "https://www.researchgate.net/profile/Antony-Alosanai-a?ev=hdr_xprf",
    scholar: "https://scholar.google.com/citations?user=kkKsxrYAAAAJ&hl=en",
    orcid: "https://orcid.org/0000-0002-6762-0103",
  },
  stats: [
    { value: "23", label: "Journal articles" },
    { value: "6", label: "Book chapters" },
    { value: "45+", label: "Citations" },
    { value: "3", label: "h-index" },
    { value: "3", label: "Journals reviewed" },
  ],
  bio: [
    "I am a hydrogeologist and consultant geophysicist working at the intersection of subsurface investigation, hydrogeochemistry, and geospatial analysis. My research focuses on characterising hard-rock and coastal aquifers in southern Tamil Nadu, with a particular interest in how azimuthal resistivity, geochemical modelling, and machine learning can be combined to support sustainable groundwater management.",
    "My doctoral work investigated fractured-basement aquifers around the Valliyur region using the Azimuthal Square Array (ASAR) method, and I continue to consult on groundwater exploration, well siting, and aquifer characterisation across India.",
  ],
  bioShort: "Hydrogeologist studying hard-rock and coastal aquifers in southern India through geophysics, hydrogeochemistry and geospatial analysis.",
  interests: [
    "Hydrogeology & groundwater exploration",
    "Applied geophysics — VES, ASAR, ERT, AMT/ADMT",
    "Coastal hydrogeology",
    "Hard-rock aquifer characterisation",
    "Hydrogeochemistry & water quality",
    "GIS, remote sensing & geospatial analysis",
    "MCDA — AHP, TOPSIS",
    "Machine learning in hydrology",
    "Sediment geochemistry & marine studies",
    "Disaster vulnerability mapping",
    "Sustainable water resource management",
    "Renewable energy site selection",
  ],
  education: [
    { degree: "Ph.D. in Geology", institution: "Manonmaniam Sundaranar University, Tirunelveli", year: "2025", detail: "Thesis: ‘Groundwater Investigations Using Azimuthal Square Array Method and Geochemical Modelling in Hard Rock Terrain, Valliyur Region, Tamil Nadu.’ Guided by Dr. A. Antony Ravindran (V.O. Chidambaram College, Thoothukudi)." },
    { degree: "M.Sc. in Geology", institution: "V.O. Chidambaram College, Thoothukudi", year: "2017", detail: "First Class with Distinction · 79%" },
    { degree: "B.Sc. in Geology", institution: "V.O. Chidambaram College, Thoothukudi", year: "2015", detail: "First Class with Distinction · 78%" },
  ],
  experience: [
    { role: "Consultant Geologist & Geophysicist", org: "Imman Geotech Pvt. Ltd.", place: "Thoothukudi, Tamil Nadu", from: "Mar 2021", to: "Present", type: "Consultant", detail: "Site investigations for groundwater exploration, well siting and aquifer characterisation across hard-rock and coastal terrains. VES, ERT, ASAR and AMT/ADMT surveys, geophysical interpretation and reporting for civil and irrigation clients." },
    { role: "Subject Matter Expert — Earth Sciences", org: "Chegg India Pvt. Ltd.", place: "Remote", from: "Aug 2018", to: "Mar 2025", type: "Freelance", detail: "Authored solutions and explanations across geology, hydrology and geophysics for an international student audience over six years." },
    { role: "Hydrogeologist", org: "Ratnam Energy Pvt. Ltd.", place: "Gujarat", from: "Jul 2017", to: "Aug 2018", type: "Full-time", detail: "Field hydrogeology and well-site supervision for energy-sector projects, including water-level monitoring, lithological logging and pumping-test interpretation." },
  ],
  skillGroups: [
    { title: "Hydrogeology & Groundwater", items: ["Groundwater flow & aquifer characterisation", "Pumping, slug & recovery tests; T and S estimation", "Well drilling supervision & lithological logging"] },
    { title: "Geophysical Surveying", items: ["Vertical Electrical Sounding (VES)", "Azimuthal Square Array Resistivity (ASAR)", "Electrical Resistivity Tomography (ERT)", "AMT / ADMT surveys", "3D aquifer & lithological modelling"] },
    { title: "Hydrogeochemistry", items: ["Major-ion, trace-element & heavy-metal analysis", "WQI · DRASTIC · contamination factor", "PCA, HCA & multivariate statistics"] },
    { title: "GIS, RS & Modelling", items: ["ArcGIS · QGIS · Google Earth Engine · ERDAS", "AHP & TOPSIS for groundwater potential mapping", "HEC-HMS · HEC-RAS · MODFLOW · GMS"] },
    { title: "Programming & ML", items: ["Python · Google Colab", "Random Forest · XGBoost · SVM · SHAP", "CA-Markov change modelling"] },
    { title: "Sediment & Marine", items: ["Marine sediment sampling", "Grain-size & heavy-mineral analysis", "Organic matter characterisation"] },
  ],
  awards: [
    { year: "2025", title: "Best Researcher Award in Earth and Planetary Sciences", body: "Book of Award · September 2025" },
    { year: "2024", title: "Associate Student Member, IAH", body: "International Association of Hydrogeologists · ID 145289 · since Aug 2024" },
  ],
  reviewedFor: ["Environmental Monitoring and Assessment", "Groundwater for Sustainable Development", "Sustainable Water Resources Management"],
  publications: [
    { year: 2026, title: "Hydrogeophysical mapping and seawater intrusion assessment in Southern Tamil Nadu, India: Application of vertical electrical sounding and Dar-Zarrouk parameters", journal: "Cleaner Water", role: "co-author", doi: "10.1016/j.clwat.2026.100266" },
    { year: 2026, title: "Integrated assessment of soil and rock penetration across the crystalline basement of the lower Thamirabarani river basin, southern India", journal: "Discover Civil Engineering", role: "co-author", doi: "10.1007/s44290-026-00451-9" },
    { year: 2026, title: "Landslide susceptibility and vulnerability assessment using GIS–AHP in the highland of Wayanad, Western Ghats, India", journal: "Discover Hazards", role: "co-author", doi: "10.1007/s44475-026-00008-5" },
    { year: 2026, title: "Seasonal variations of inner shelf sediment dynamics and granulometric characteristics along the Nagapattinam coast of the Cauvery basin, Southern India", journal: "Discover Oceans", role: "co-author", doi: "10.1007/s44289-025-00109-x" },
    { year: 2026, title: "Hydrogeochemical variability and health risk assessment of heavy metals in groundwater of Srivaikundam region, Southern India", journal: "Environmental Geochemistry and Health", role: "co-author", doi: "10.1007/s10653-025-02914-x" },
    { year: 2025, title: "Decadal dynamics of urban heat islands in a coastal industrial region of India: remote sensing insights for sustainable urban planning", journal: "Environment, Development and Sustainability", role: "co-author", doi: "10.1007/s10668-025-07153-9" },
    { year: 2025, title: "Provenance and coastal dynamics inferred through textural parameters and heavy mineral contents of the shoreline sediments, Tamil Nadu, southeast India", journal: "J. Indian Assoc. Sedimentologists", role: "co-author", doi: "10.51710/jias.v42iI.445" },
    { year: 2025, title: "Quantifying spatiotemporal LULC change and urban expansion using geospatial modelling and Shannon's entropy in a coastal city of India", journal: "Discover Civil Engineering", role: "co-author", doi: "10.1007/s44290-025-00341-6" },
    { year: 2025, title: "Spatial modelling of groundwater potential zones in the Neyyar Basin using machine learning and morphometric analysis", journal: "Scientific Reports", role: "co-author", doi: "10.1038/s41598-025-20000-1", featured: true },
    { year: 2025, title: "Characterization of fractured basement aquifers using square-array VES, azimuthal resistivity analysis and 3D lithological modelling: an integrated approach for sustainable groundwater management", journal: "Water Conservation Science and Engineering", role: "first author", doi: "10.1007/s41101-025-00444-2", featured: true },
    { year: 2025, title: "Integrating Remote Sensing and Geospatial-Based Comprehensive MCDA Approach for Sustainable Coastal Solar Site Selection in Southern India", journal: "ISPRS Int. J. Geo-Information", role: "co-author", doi: "10.3390/ijgi14100377" },
    { year: 2025, title: "Comprehensive hydrogeochemical characterization and seasonal water quality index analysis for sustainable groundwater management in Valliyur region, Southern Tamil Nadu, India", journal: "Scientific Reports", role: "first author", doi: "10.1038/s41598-025-18285-3", featured: true },
    { year: 2025, title: "Hydrogeophysical characterization of groundwater and subsurface geology using VES and GMS modeling in Srivaikundam region, Southern Tamil Nadu", journal: "Modeling Earth Systems and Environment", role: "co-author", doi: "10.1007/s40808-025-02542-5" },
    { year: 2025, title: "Mapping of cyclone disaster vulnerability using geospatial techniques and AHP: Implications for resilient urban planning in coastal city of Southern Tamil Nadu", journal: "Disaster Advances", role: "co-author", doi: "10.25303/187da050060" },
    { year: 2025, title: "Flood susceptibility assessment for coastal villages of Southern Tamil Nadu: an integrated GIS and AHP approach", journal: "Disaster Advances", role: "co-author", doi: "10.25303/186da018027" },
    { year: 2025, title: "An application of remote sensing and GIS used in groundwater potential zones for sustainable urban development in coastal areas between Chettikulam and Kolachal, southern India", journal: "Applied Geomatics", role: "co-author", doi: "10.1007/s12518-024-00604-4" },
    { year: 2024, title: "Synergizing hazard resilience and renewable energy potential for smart coastal development: a GIS-MCDA approach in Thoothukudi, India", journal: "Nanotechnology Perceptions", role: "co-author" },
    { year: 2024, title: "Multicriteria analysis of groundwater potential in Valliyur region, Tamil Nadu: integrating remote sensing, GIS and AHP", journal: "Water Conservation Science and Engineering", role: "first author", doi: "10.1007/s41101-024-00285-5", featured: true },
    { year: 2024, title: "Geophysical exploration of tectonic signatures in proterozoic quartzite of the Kovilpatti region, southern India", journal: "Carbonates and Evaporites", role: "co-author", doi: "10.1007/s13146-024-00962-5" },
    { year: 2024, title: "Geophysical and geochemical studies on sinking stream occurrence in Ayankulam village of South Tamil Nadu, India", journal: "Proc. Indian National Science Academy", role: "co-author", doi: "10.1007/s43538-024-00287-w" },
    { year: 2022, title: "Geophysical and geochemical prospecting for submarine groundwater discharge in a karst leaky aquifer from Valliyur Hills to Uvari Beach", journal: "Modeling Earth Systems and Environment", role: "first author", doi: "10.1007/s40808-022-01412-8", featured: true },
    { year: 2022, title: "Integrated geophysical and geochemical assessment of submarine groundwater discharge in coastal terrace of Tiruchendur, Southern India", journal: "Applied Water Science", role: "co-author", doi: "10.1007/s13201-021-01553-8" },
    { year: 2020, title: "A case study of freshwater discharge in porous calcarenite formation in coastal terrace at Manapad, South India", journal: "Carbonates and Evaporites", role: "co-author", doi: "10.1007/s13146-020-00641-1" },
  ],
  bookChapters: [
    { year: 2025, title: "Interacting RS and GIS to GWPZ in Urban Development Site Suitability Analysis of Kovilpai Region, Southern Tamil Nadu, India" },
    { year: 2024, title: "Groundwater Exploration in Fractured Charnockite Formation for Irrigation at Alangulam, Tamil Nadu, India" },
    { year: 2023, title: "Groundwater Management Studies Using Geological and 2D ERI Techniques in Ariyanayakipuram Village, Tirunelveli, Tamil Nadu, India" },
    { year: 2022, title: "Groundwater Exploration Study using 2D ERI and Geochemical Mapping in Muruganpuram, Vallanadu, Tamil Nadu" },
    { year: 2022, title: "Freshwater discharge in coastal aquifer study using electrical resistivity and geochemical method in Sahupuram, Thoothukudi" },
    { year: 2022, title: "Crystalline limestone investigation study in Podupatti and Pungarvattam, Ettayapuram, Thoothukudi" },
  ],
  // Featured projects derived from research
  featuredProjects: [
    { tag: "Doctoral Research", title: "Fractured-basement aquifers, Valliyur", body: "Square-array VES, azimuthal resistivity and 3D lithological modelling to characterise hard-rock aquifers and inform sustainable groundwater management.", year: "2022 – 2025", journal: "Water Conservation Science and Engineering" },
    { tag: "Coastal Hydrogeology", journal: "Modeling Earth Systems and Environment", title: "Submarine groundwater discharge — Valliyur Hills to Uvari Beach", body: "Integrated geophysical and geochemical prospecting in a karst leaky aquifer to map freshwater discharge into the Bay of Bengal.", year: "2022" },
    { tag: "Geospatial × ML", journal: "Scientific Reports", title: "Groundwater potential zones, Neyyar Basin", body: "Random Forest, XGBoost and morphometric analysis combined with GIS layers to model groundwater potential at basin scale.", year: "2025" },
    { tag: "Hydrogeochemistry", journal: "Scientific Reports", title: "Seasonal water-quality index, Valliyur", body: "Major-ion analysis, WQI and multivariate statistics across pre- and post-monsoon seasons to support drinking-water management.", year: "2025" },
    { tag: "MCDA", journal: "ISPRS IJGI", title: "Coastal solar-site selection, southern India", body: "GIS-based AHP/TOPSIS to identify suitable sites for utility-scale solar deployment along the Tamil Nadu coast.", year: "2025" },
    { tag: "Disaster Mapping", journal: "Disaster Advances", title: "Cyclone vulnerability, Thoothukudi", body: "Geospatial AHP modelling of physical and social vulnerability for resilient urban planning in a coastal city.", year: "2025" },
  ],
  references: [
    { name: "Dr. A. Antony Ravindran", role: "Research Supervisor · Asst. Professor, PG & Research Dept. of Geology", org: "V.O. Chidambaram College, Thoothukudi", email: "antonicogeo@gmail.com", phone: "+91 90801 87893" },
    { name: "Dr. V. Stephen Pitchaimani", role: "Assistant Professor, Department of Geology", org: "V.O. Chidambaram College, Thoothukudi", email: "vsssgeo@gmail.com", phone: "+91 98406 80473" },
    { name: "Dr. N. Gladwin Gnana Asir", role: "Asst. Professor of Marine Science", org: "SDMRI, Thoothukudi", email: "gladwinasir@gmail.com", phone: "+91 89036 82383" },
  ],
  resumePath: "uploads/resume_file-1777330838235.docx",
  resumePdfPath: "uploads/Promilton_Biodata_CV_2026.pdf",
};
